export const idUnset = 'some_secret_identification_number_or_string';
export const idCorrect = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InNvbWVfZW5jb2RlZF9pZGVudGlpdHkiLCJpYXQiOjE1NjY4MTE1OTcsImV4cCI6MTU2Njg5Nzk5N30.oCXhqT4Ri-k7RIqlgIHVFvGGwmxIzBwyzqbXIG0JwyE';
export const idWrong = 'eyJhbGciOiJIUzI1NiIsInR5cCI6bkpXVCJ9.eyJpZCI6InNvbWVfZW5jb2RlZF9pZGVudGlpdHkiLCJpYXQiOjE1NjY4MTE1OTcsImV4cCI6MTU2Njg5Nzk5N30.oCXhqT4Ri-k7RIqlgIHVFvGGwmxIzBwyzqbXIG0JwyE';
export const invalidUserToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxNSwiZW1haWwiOiJhbG1pQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6ImFkZXdhbGUiLCJsYXN0TmFtZSI6Im9sYW95ZSJ9LCJpYXQiOjE1Njg0NzgyMDR9.gvLifCTuBsceD3JjFc6sdf09Z8UkHP6BVcIAI1ktWlI';
